version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oncology_pharmacy_dev
    volumes:
      - pg-onco:/var/lib/postgresql/data
    ports:
      - 5432:5432

